apiVersion: v1
kind: Pod
metadata:
  name: tech5
  labels:
    app: tech5-fiap
spec:
  containers:
  - name: tech5
    image: jbaldijr/tech5:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tech5-service
spec:
  selector:
    app: tech5-fiap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
